# Generated by Django 5.0.6 on 2024-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encountered_birds',
            field=models.ManyToManyField(blank=True, related_name='users_who_saw', to='bird.species'),
        ),
    ]
